name: self-hosted-runner

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: codebuild-github-hosted-runner-connect-${{ github.run_id }}-${{ github.run_attempt }}

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_USER: $DB_USER
          MYSQL_PASSWORD: $DB_PASSWORD
          MYSQL_HOST: $DB_HOST
          MYSQL_DATABASE: test

    steps:
      - uses: actions/checkout@v4

      - name: Setup flyway
        run: wget -qO- https://download.red-gate.com/maven/release/com/redgate/flyway/flyway-commandline/10.11.1/flyway-commandline-10.11.1-linux-x64.tar.gz | tar -xvz && sudo ln -s `pwd`/flyway-10.11.1/flyway /usr/local/bin
      
      - name: Run Flyway Migration
        env:
          FLYWAY_URL: jdbc:mysql://$DB_HOST:3306/test
          FLYWAY_USER: $DB_USER
          FLYWAY_PASSWORD: $DB_PASSWORD
          FLYWAY_SCHEMAS: test
        run: |
          echo ${{env.FLYWAY_URL}}
          echo ${{env.FLYWAY_USER}}
          flyway info
      