name: self-hosted-runner

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: codebuild-github-hosted-runner-connect-${{ github.run_id }}-${{ github.run_attempt }}

#    services:
#      mysql:
#        image: mysql:8.0
#        env:
#          MYSQL_USER: $DB_USER
#          MYSQL_PASSWORD: $DB_PASSWORD
#          MYSQL_HOST: $DB_HOST
#          MYSQL_DATABASE: test
    steps:
      - uses: actions/checkout@v4

      - name: Install DB Client
        run: |
          sudo apt-get update && apt-get install -y mysql-server

      - name: Test DB connection
        run: |
          mysql -e "SHOW DATABASES;" -u $DB_USER -h $DB_HOST -p$DB_PASSWORD
